import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ClientErrorHandlers from "./ClientErrorHandlers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400","600","700","800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        {/* Client-side error handlers to suppress noisy third-party fetch errors in preview/dev */}
        <script dangerouslySetInnerHTML={{__html: `/* placeholder to keep module context for React */`}} />
        {/* Client component mounts here */}
        <div id="__client_error_handlers__" />
        {children}
      </body>
    </html>
  );
}
